from Essence_Helper import WeaponIndex, Stat

index = WeaponIndex()

index.add_weapon("Tarr 11", Stat.MAIN_ATTRIBUTE_BOOST, Stat.ATTACK_BOOST)
index.add_weapon("Jiminy 12", Stat.MAIN_ATTRIBUTE_BOOST, Stat.ATTACK_BOOST)
index.add_weapon("Peco 5", Stat.MAIN_ATTRIBUTE_BOOST, Stat.ATTACK_BOOST)
index.add_weapon("Howling Guard", Stat.INTELLECT_BOOST, Stat.ATTACK_BOOST, Stat.SUPPRESSION)
index.add_weapon("Long Road", Stat.STRENGTH_BOOST, Stat.ORIGINIUM_ARTS_BOOST, Stat.PURSUIT)
index.add_weapon("Aggeloslayer", Stat.WILL_BOOST, Stat.ORIGINIUM_ARTS_BOOST, Stat.SUPPRESSION)
index.add_weapon("Pathfinder's Beacon", Stat.AGILITY_BOOST, Stat.ATTACK_BOOST, Stat.INSPIRING)
index.add_weapon("Industry 0.1", Stat.STRENGTH_BOOST, Stat.ATTACK_BOOST, Stat.SUPPRESSION)
index.add_weapon("Contingent Measure", Stat.AGILITY_BOOST, Stat.PHYSICAL_DMG_BOOST, Stat.SUPPRESSION)
index.add_weapon("Quencher", Stat.WILL_BOOST, Stat.HP_BOOST, Stat.CRUSHER)
index.add_weapon("Wave Tide", Stat.INTELLECT_BOOST, Stat.ATTACK_BOOST, Stat.PURSUIT)
index.add_weapon("Hypernova Auto", Stat.INTELLECT_BOOST, Stat.ORIGINIUM_ARTS_BOOST, Stat.INSPIRING)
index.add_weapon("Fluorescent Roc", Stat.WILL_BOOST, Stat.ATTACK_BOOST, Stat.SUPPRESSION)
index.add_weapon("Aspirant", Stat.AGILITY_BOOST, Stat.PHYSICAL_DMG_BOOST, Stat.TWILIGHT)
index.add_weapon("Wild Wanderer", Stat.INTELLECT_BOOST, Stat.ELECTRIC_DMG_BOOST, Stat.INFLICTION)
index.add_weapon("Stanza of Memorials", Stat.INTELLECT_BOOST, Stat.ATTACK_BOOST, Stat.TWILIGHT)
index.add_weapon("Rational Farewell", Stat.STRENGTH_BOOST, Stat.HEAT_DMG_BOOST, Stat.PURSUIT)
index.add_weapon("Ancient Canal", Stat.STRENGTH_BOOST, Stat.ARTS_DMG_BOOST, Stat.BRUTALITY)
# Progress: 20/62
index.add_weapon("Monaihe", Stat.WILL_BOOST, Stat.ULTIMATE_GAIN_BOOST, Stat.INSPIRING)
index.add_weapon("Chimeric Justice", Stat.STRENGTH_BOOST, Stat.ULTIMATE_GAIN_BOOST, Stat.BRUTALITY)
index.add_weapon("OBJ Heavy Burden", Stat.STRENGTH_BOOST, Stat.HP_BOOST, Stat.EFFICACY)
index.add_weapon("Opus: The Living", Stat.AGILITY_BOOST, Stat.ORIGINIUM_ARTS_BOOST, Stat.INFLICTION)
index.add_weapon("OBJ Razorhorn", Stat.WILL_BOOST, Stat.PHYSICAL_DMG_BOOST, Stat.INFLICTION)
index.add_weapon("OBJ Velocitous", Stat.AGILITY_BOOST, Stat.ULTIMATE_GAIN_BOOST, Stat.DETONATE)
index.add_weapon("Sundering Steel", Stat.AGILITY_BOOST, Stat.PHYSICAL_DMG_BOOST, Stat.COMBATIVE)
index.add_weapon("Seeker of Dark Lung", Stat.STRENGTH_BOOST, Stat.ULTIMATE_GAIN_BOOST, Stat.DETONATE)
index.add_weapon("Cohesive Traction", Stat.WILL_BOOST, Stat.ELECTRIC_DMG_BOOST, Stat.SUPPRESSION)
index.add_weapon("Fortmaker", Stat.INTELLECT_BOOST, Stat.ULTIMATE_GAIN_BOOST, Stat.INSPIRING)
# Progress: 30/62
index.add_weapon("Finishing Call", Stat.STRENGTH_BOOST, Stat.HP_BOOST, Stat.MEDICANT)
index.add_weapon("Finchaser 3.0", Stat.STRENGTH_BOOST, Stat.CRYO_DMG_BOOST, Stat.SUPPRESSION)
index.add_weapon("OBJ Arts Identifier", Stat.INTELLECT_BOOST, Stat.ARTS_DMG_BOOST, Stat.PURSUIT)
index.add_weapon("Twelve Questions", Stat.AGILITY_BOOST, Stat.ATTACK_BOOST, Stat.INFLICTION)
index.add_weapon("OBJ Edge of Lightness", Stat.AGILITY_BOOST, Stat.ATTACK_BOOST, Stat.FLOW)
index.add_weapon("Freedom to Proselytize", Stat.WILL_BOOST, Stat.TREATMENT_EFFICIENCY_BOOST, Stat.MEDICANT)
index.add_weapon("Sundered Prince", Stat.STRENGTH_BOOST, Stat.CRITICAL_RATE_BOOST, Stat.CRUSHER)
index.add_weapon("White Night Nova", Stat.MAIN_ATTRIBUTE_BOOST, Stat.ARTS_DMG_BOOST, Stat.INFLICTION)
index.add_weapon("Grand Vision", Stat.AGILITY_BOOST, Stat.ATTACK_BOOST, Stat.INFLICTION)
index.add_weapon("Rapid Ascent", Stat.MAIN_ATTRIBUTE_BOOST, Stat.CRITICAL_RATE_BOOST, Stat.TWILIGHT)
# Progress: 40/62
index.add_weapon("Never Rest", Stat.WILL_BOOST, Stat.ATTACK_BOOST, Stat.FLOW)
index.add_weapon("Eminent Repute", Stat.MAIN_ATTRIBUTE_BOOST, Stat.PHYSICAL_DMG_BOOST, Stat.BRUTALITY)
index.add_weapon("Opus: Etch Figure", Stat.WILL_BOOST, Stat.NATURE_DMG_BOOST, Stat.SUPPRESSION)
index.add_weapon("Navigator", Stat.INTELLECT_BOOST, Stat.CRYO_DMG_BOOST, Stat.INFLICTION)
index.add_weapon("Chivalric Virtues", Stat.WILL_BOOST, Stat.HP_BOOST, Stat.MEDICANT)
index.add_weapon("Khravengger", Stat.STRENGTH_BOOST, Stat.ATTACK_BOOST, Stat.DETONATE)
index.add_weapon("Exemplar", Stat.MAIN_ATTRIBUTE_BOOST, Stat.ATTACK_BOOST, Stat.SUPPRESSION)
index.add_weapon("Oblivion", Stat.INTELLECT_BOOST, Stat.ORIGINIUM_ARTS_BOOST, Stat.TWILIGHT)
index.add_weapon("Valiant", Stat.AGILITY_BOOST, Stat.PHYSICAL_DMG_BOOST, Stat.FRACTURE)
index.add_weapon("Artzy Tyrannical", Stat.INTELLECT_BOOST, Stat.CRITICAL_RATE_BOOST, Stat.FRACTURE)
# Progress: 50/62
index.add_weapon("Wedge", Stat.MAIN_ATTRIBUTE_BOOST, Stat.CRITICAL_RATE_BOOST, Stat.INFLICTION)
index.add_weapon("Detonation Unit", Stat.MAIN_ATTRIBUTE_BOOST, Stat.ARTS_DMG_BOOST, Stat.DETONATE)
index.add_weapon("Delivery Guaranteed", Stat.WILL_BOOST, Stat.ULTIMATE_GAIN_BOOST, Stat.PURSUIT)
index.add_weapon("Clannibal", Stat.MAIN_ATTRIBUTE_BOOST, Stat.ORIGINIUM_ARTS_BOOST, Stat.INFLICTION)
index.add_weapon("JET", Stat.MAIN_ATTRIBUTE_BOOST, Stat.ATTACK_BOOST, Stat.SUPPRESSION)
index.add_weapon("Umbral Torch", Stat.INTELLECT_BOOST, Stat.HEAT_DMG_BOOST, Stat.INFLICTION)
index.add_weapon("Former Finery", Stat.WILL_BOOST, Stat.HP_BOOST, Stat.EFFICACY)
index.add_weapon("Mountain Bearer", Stat.AGILITY_BOOST, Stat.PHYSICAL_DMG_BOOST, Stat.EFFICACY)
index.add_weapon("Dreams of the Starry Beach", Stat.INTELLECT_BOOST, Stat.TREATMENT_EFFICIENCY_BOOST, Stat.INFLICTION)
index.add_weapon("Thermite Cutter", Stat.WILL_BOOST, Stat.ATTACK_BOOST, Stat.FLOW)
# Progress: 60/62
index.add_weapon("Thunderberge", Stat.STRENGTH_BOOST, Stat.HP_BOOST, Stat.MEDICANT)
index.add_weapon("Forgeborn Scathe", Stat.INTELLECT_BOOST, Stat.ATTACK_BOOST, Stat.TWILIGHT)
